### ISSUE TITLE
Pattern: iterating over rows in a data frame

### ISSUE THREAD

**Issue by jennybc** [tidyverse/tidyverse.org#112]
Idea for a blog post in the programming category.

Iterating over rows in a data frame ...
This is a common problem where there is little consensus re: best way to proceed.

Capturing a few snippets of Slack discussion to jog our memories:

  * Do you really need to iterate over rows? Are you overlooking a vectorized solution? Applies especially to string manipulation. (@hadley this is related to the question of whether to attack a problem row- or column-wise)
  * What about `pmap()`?
    - Ways to define `.f` (explicitly + globally, explicitly + inline + anonymously, the `~` shorthand)
    - Tension in pipelines when multiple functions are operating on the tibble (e.g. `pmap()` inside `mutate()`), competing meanings for `.`
    - Arguments of `.f`: names vs position, absorbing unused args with `...`
    - Use `rlang::call_inspect()` to see what's going on, e.g. `purrr::pmap(mtcars, rlang::call_inspect)`
    - `pmap()` is expensive because it disaggregates the tibble. E.g. you don't want to use it naively with a social survey tibble with hundreds of columns just to work on a few variables.
  * What are you trying to optimize? Performance? Readability? No dependencies? Pipe-ability?

**Comment by jennybc** [comment]
The first of 2 twitter threads by @daattali on this matter: [what's a safe way to iterate over rows of a dataframe?](https://twitter.com/daattali/status/761058049859518464) lead to lots of proposed solutions.

@wch can you link to the RPub you created in response to Dean's tweet, with various options and exploring performance? I'm having trouble finding it.

**Comment by daattali** [comment]
@jennybc I think this is the rpubs doc you want https://rpubs.com/wch/200398

**Comment by jennybc** [comment]
I've just agreed to do a webinar on this 2018-04-11.

The general title will something about "split apply combine": basically working on rows or groups of rows in a data frame.

I will probably write this post around the same time, i.e. kill 2 birds with one stone.

I anticipate working lots of small concrete examples exploring different approaches to common problem patterns that occur.

I'll certainly draw on the sections near the bottom of this: https://jennybc.github.io/purrr-tutorial/bk01_base-functions.html

Happy to take input.

**Comment by jennybc** [comment]
Abstract I just gave for the webinar:

4/11 - Thinking inside the box: you can do that inside a data frame?! - Jenny Bryan
Abstract: The data frame is a crucial data structure in R and, especially, in the tidyverse. Working on a column or a variable is a very natural operation, which is great. But what about row-oriented work? That also comes up frequently and is more awkward. In this webinar I’ll work through concrete code examples, exploring patterns that arise in data analysis. We’ll discuss the general notion of “split-apply-combine”, row-wise work in a data frame, splitting vs. nesting, and list-columns.

**Comment by hadley** [comment]
Will handle this shortly when I announce new dplyr rowwise features.
