### ISSUE TITLE
FIgure out *Contents* sidebar

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/tidyverse.org#124]
Currently, the *Contents* sidebar is only populated for posts written directly in markdown, e.g.
* [![contents1-min](https://user-images.githubusercontent.com/831732/36733354-56393358-1b9e-11e8-99fe-1facbf9f84c6.png)](https://github.com/tidyverse/tidyverse.org/blob/master/content/articles/2017-08-08-contributing.md)
* [![contents2-min](https://user-images.githubusercontent.com/831732/36733394-79c6b8cc-1b9e-11e8-8ad1-93a43cdea667.png)](https://github.com/tidyverse/tidyverse.org/blob/master/content/articles/2017-08-googledrive-initial-release.md)

For posts written in `.Rmd`, headers are _not_ added to contents. It's possible that this looks particularly weird right now because there are also no upcoming events, but I think it would also make the articles more "browseable."
* [![contents3-min](https://user-images.githubusercontent.com/831732/36733451-ae34c0fe-1b9e-11e8-8141-e17a0a9ccbac.png)](https://www.tidyverse.org/articles/2018/02/usethis-1-3-0/)

_n.b. Can get TOC to show up at the top of the post with the code below, but that's not the desired behaviour._
```yaml
output:
  blogdown::html_page:
    toc: true
```

**Comment by hadley** [comment]
I think this is now solved thanks to @jimhester
