### ISSUE TITLE
Add list of domain-specific tidyverse friendly packages to tidyverse.org/packages

### ISSUE THREAD

**Issue by rudeboybert** [tidyverse/tidyverse.org#13]
At the end of  [Packages](https://www.tidyverse.org/packages/) page of tidyverse.org, how about adding a "Domain Specific tidyverse Friendly Packages" (or something to that effect) section that includes list of domain/vertical-specific packages that play nice within `tidyverse` ecosystem? Examples:

* @rudeboybert, @ismayc, @jchunn's [`fivethirtyeight`](https://github.com/rudeboybert/fivethirtyeight) under "Data Journalism" and "Education"
* @walkerke's [`tidycensus`](https://github.com/walkerke/tidycensus) under "Demography"
* @mdancho84 and @DavisVaughan's [`tidyquant`](https://github.com/business-science/tidyquant) under "Finance"
 
and eventually domain-specific packages with [reverse depends/imports/suggests](https://cran.r-project.org/web/packages/tidyverse/index.html) of `tidyverse`

**Comment by hadley** [comment]
I really like this idea, but I need to think about the wording a bit - I'd like to come up with a naming scheme that I can use consistently:

* Core tidyverse: packages loaded when you do `library(tidyverse)`
* ???: packages that live in the [tidyverse organisation](http://github.com/tidyverse)
* ???: packages contributed by the community in line with the tidyverse philsophy

Any ideas? Core, central, and community?

**Comment by ismayc** [comment]
I like the three C's as you have suggested.  "Community" especially signifies that others are working to develop packages following the tidy framework.

**Comment by DavisVaughan** [comment]
This is a nice idea. I think that core and community are good fits, but is central too similar to core? Alternatives might be:

- collection - Straight from the tidyverse.org github page description, "The tidyverse is a collection of R packages that share common principles and are designed to work together seamlessly."

Core, Collection, Community

- common - Inspired by the old [tidyverse.tidyverse.org](tidyverse.tidyverse.org), "...also installs a selection of other packages that you’re likely to use frequently, but probably not in every analysis."

Core, Common, Community

**Comment by hadley** [comment]
Regardless of what we pick, this is note to remind me that it'll probably be easier to have one page per area (so community doesn't end up buried at the bottom), which will require some changes to the top-level nav.

**Comment by hadley** [comment]
cc @jennybc since she's great at naming things

**Comment by jennybc** [comment]
I hear naming things is really hard.

**Comment by jennybc** [comment]
I quite like "Core, Common, Community" from @DavisVaughan.

I also think it is helpful to have a super-clear explanation of core vs common (or whatever). Is it and will it likely remain this?

  * core and common live in the tidyverse organization
  * core and common are installed as part of `install.packages("tidyverse")`
  * only core are loaded by `library(tidyverse)`

**Comment by rudeboybert** [comment]
A Venn diagram should do the trick! I'm on the road now; I'll post one later.

**Comment by hadley** [comment]
The Venn diagram should be fairly simple since it's a strict containment hierarchy 😄.  But this would be a good image for the future "packages index" page, which would then link out to the individual core, common, and community pages.

**Comment by rudeboybert** [comment]
Prototype:

![tidyverse venn diagram](https://user-images.githubusercontent.com/4574203/29094804-ad6735b2-7c5c-11e7-94f6-313c62a2264b.png)

* I like "Commonly-Used" instead of "Common" as the latter is a bit ambiguous.
* The community portion could be a word cloud as well. Notice how there is no set surrounding it, suggesting the possibilities are endless!
* I just noticed my legend for the dashed line is off, should read "not necessarily loaded"
* FWIW Google Drawing [link](https://docs.google.com/drawings/d/10zrWCCxNaDa8wt4fqsoU7Szk6KSutkmeG1EKXG1aHag/edit)

**Comment by hadley** [comment]
I like the idea but I think it's going to be too much work to maintain (especially if you want to hyperlink the logos to the right place) - but this will be great for presentations etc!  For the website, I think a simple diagram of core + ??? + community will suffice.

Commonly used isn't quite the right framing - it's not how often the packages are used, it's the fact that the tidyverse organisation/team is behind them.

**Comment by DavisVaughan** [comment]
With that in mind, "certified" popped into my head. It doesn't have the same hard C sound as the other two and is past tense so maybe it sounds a little odd, but it doesn't look too bad and I think captures the spirit of what you're getting at a little more. Certified packages maintained by the tidyverse organization.

Core, Certified, Community

**Comment by hadley** [comment]
I'm being very picky now, but I was thinking about keeping certified in my back pocket for some future use (i.e. offering some process to certify community packages).

**Comment by jennybc** [comment]
The word that most comes to mind is "in**C**luded". As in batteries 🔋. It's included when you install the tidyverse package, because we suspect you will eventually want to use it.

**Comment by hadley** [comment]
Given that this is now almost 3 years later, and the number of packages that could plausible be included in this list has grown considerably, I think it's best to just close this issue.
