### ISSUE TITLE
Add google analytics to tidyverse package sites

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/tidyverse.org#136]
## now happening through tidytemplate update…

- [x]  tidyverse.org
- [x] [dplyr](https://github.com/tidyverse/dplyr) (https://github.com/tidyverse/dplyr/pull/3453)
- [x] [tidyr](https://github.com/tidyverse/tidyr) (pending https://github.com/tidyverse/tidyr/pull/440)
- [x] [ggplot2](https://github.com/tidyverse/ggplot2) (see https://github.com/tidyverse/ggplot2/pull/2487)
- [ ] [broom](https://github.com/tidyverse/broom)
- [ ] [magrittr](https://github.com/tidyverse/magrittr)
- [ ] [purrr](https://github.com/tidyverse/purrr)
- [ ] [readr](https://github.com/tidyverse/readr)
- [ ] [tidyverse](https://github.com/tidyverse/tidyverse) (pending https://github.com/tidyverse/tidyverse/pull/123)
- [ ] [readxl](https://github.com/tidyverse/readxl)
- [ ] [lubridate](https://github.com/tidyverse/lubridate)
- [ ] [reprex](https://github.com/tidyverse/reprex)
- [ ] [modelr](https://github.com/tidyverse/modelr)
- [ ] [glue](https://github.com/tidyverse/glue)
- [ ] [stringr](https://github.com/tidyverse/stringr) (pending https://github.com/tidyverse/stringr/pull/227)
- [x] [haven](https://github.com/tidyverse/haven)
- [ ] [forcats](https://github.com/tidyverse/forcats) (PR https://github.com/tidyverse/forcats/pull/120)
- [ ] [tibble](https://github.com/tidyverse/tibble)
- [ ] [dbplyr](https://github.com/tidyverse/dbplyr)
- [ ] [googledrive](https://github.com/tidyverse/googledrive)
- [x] style
- [ ] [hms](https://github.com/tidyverse/hms)
- [ ] [tidyselect](https://github.com/tidyverse/tidyselect)
- [ ] [blob](https://github.com/tidyverse/blob)
- [x] tidytemplate
- [ ] [googlesheets4](https://github.com/tidyverse/googlesheets4)

## Add same to referral exclusion

- [ ] Subdomains to[ referral exclusion](https://support.google.com/analytics/answer/2795830?hl=en)

**Comment by hadley** [comment]
Done via tidytemplate update
