### ISSUE TITLE
Documentation of purrr::depth instead of purrr::vec_depth on tidyverse.org

### ISSUE THREAD

**Issue by EdwinTh** [tidyverse/tidyverse.org#141]
I found this [site](http://purrr.tidyverse.org/reference/depth) through Google. However, there appeared to be no function called `depth` in `purrr`(v 0.2.4). When looking further I found out it is named `vec_depth` in the package, you probably need to update the function name on the website.

**Comment by batpigandme** [comment]
Thanks, Edwin. I'll update stat.

**Comment by batpigandme** [comment]
Just realised where this issue was/is — no big deal, but just FFR, you can file package website issues directly in the package repo!
