### ISSUE TITLE
Decide if "tidyverse" should be capitalized

### ISSUE THREAD

**Issue by richierocks** [tidyverse/tidyverse.org#169]
Just had a discussion at DataCamp on whether "tidyverse" needs to be capitalized (when not referring to the package), and it seems that even here it is written both ways. See, for example,

![screenshot 2018-06-26 11 16 34](https://user-images.githubusercontent.com/197589/41922140-70425382-7932-11e8-9a55-28629b068ae2.png)

I'd like some official guidance on capitalization. Thanks!

**Comment by hadley** [comment]
If you're talking about the package, never capitalise it. If you're talking about it more generally, capitalise only at the start of sentences.
