### ISSUE TITLE
Add article tags

### ISSUE THREAD

**Issue by maelle** [tidyverse/tidyverse.org#185]
:wave: here! Thanks for great articles full of wisdom!

I ~saw~ didn't see (thanks @batpigandme) there are Categories at the top-right corner of https://www.tidyverse.org/articles/ which is awesome for browsing articles.

I wonder whether it'd make sense to also make these tags available from each article e.g. if I read https://www.tidyverse.org/articles/2018/07/carpe-talk/ and want to read similar articles on your website. 🤓

**Comment by batpigandme** [comment]
Should we so desire, I think it'd be basically the same code used to list them in the article stubs (basically putting this here so I don't forget).
```html
<div class="itemTag">
                  {{- range .Params.categories -}}
                  <a href="{{ relURL (print "/categories/" . | urlize) }}">{{ . }}</a>
                  {{ end -}}
 </div>
```

**Comment by maelle** [comment]
The articles also don't display their own publication date by the way :wink:

**Comment by batpigandme** [comment]
Notes: Articles now display their authors and publish date. We're adding tags (in the works), but won't be adding categories inside of the posts (since they're 90% packages).

**Comment by maelle** [comment]
:tada:, cool! It makes me feel like clicking on author names to see all their posts at once :wink:

**Comment by batpigandme** [comment]
> It makes me feel like clicking on author names to see all their posts at once

We intentionally don't have that because there's so little relationship between the author of a post and its content (e.g. I write posts for package releases that aren't mine regularly). We'll be adding tags, though, in order to make things more navigable.

**Comment by hadley** [comment]
Would be good to finish this off now that the new system has been up and running for a while.

**Comment by batpigandme** [comment]
Stashing notes here: @apreshill has the code for this, depends on Hugo > 0.65.1, which is fine for us.
