### ISSUE TITLE
Review accessibility

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidyverse.org#202]

**Comment by batpigandme** [comment]
Just one small piece, but we should figure out how to do alt-text for figures generated in RMarkdown (naming chunks can give the file an informative name, but there's still no alt-text property).

**Comment by maelle** [comment]
Sorry to comment here if not relevant. @batpigandme I've started using fig.cap (chunk option) in my posts (not always) to get the alt text. Maybe writing a linter for Markdown websites checking alt text could be a project for Forwards (for my own site it'd flag all posts...).

**Comment by hadley** [comment]
Duplicate of #374
