### ISSUE TITLE
Site needs search

### ISSUE THREAD

**Issue by jennybc** [tidyverse/tidyverse.org#208]

**Comment by batpigandme** [comment]
Agreed. The blogdown theme I use came with search pre-included, but are there any preferences re. which search implementation we should use (embeddable script, vs one of the hugo indexing tools)?
https://gohugo.io/tools/search/

**Comment by jennybc** [comment]
This is not my wheelhouse so I hope someone else can help think this through

**Comment by batpigandme** [comment]
Per discussion with @hadley, turns out we actually don't want this!

**Comment by hadley** [comment]
Closing, since I really don't think we want to bother with search at this time.
