### ISSUE TITLE
category typo

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidyverse/tidyverse.org#234]
It appears that https://www.tidyverse.org/articles/2018/10/ggplot2-3-1-0/ is mistakenly categorized as "packages" instead of "package" which leads to this
![screen shot 2018-11-16 at 5 48 44 pm](https://user-images.githubusercontent.com/14034784/48655234-4af3f380-e9c9-11e8-9985-4310a6ec3317.png)

**Comment by batpigandme** [comment]
Whoops, my bad! Thanks, Emil.
