### ISSUE TITLE
Fixes to dplyr 0.8.0 post

### ISSUE THREAD

**Issue by jennybc** [tidyverse/tidyverse.org#246]
I can't make a PR myself atm, but some small tweaks:

> In this example, we group by `f1` then `x`. At the first layer, grouping on `f1` creates two groups. Each of these grouops is then subdivided 

I think "grouping on `f1` creates two groups" should be THREE groups.

Also "grouops" --> "groups"

@romainfrancois @batpigandme

**Comment by romainfrancois** [comment]
ouch. Thanks. I'll need to do a PR anyway to fix what `count()` shows. That backfired quickly.

**Comment by jennybc** [comment]
Can the number of visible rows for tibble printing be increased so more of the small examples are fully revealed?

**Comment by batpigandme** [comment]
> Also "grouops" --> "groups"

I swear, I caught that one! (>ლ)

@romainfrancois, just LMK when you've made all the edits you want to

**Comment by romainfrancois** [comment]
tomorrow, likely
