### ISSUE TITLE
line height of code blocks

### ISSUE THREAD

**Issue by jimhester** [tidyverse/tidyverse.org#260]
The line heights for code blocks feel really big to me, looks like it is set to 2x the font size (28px). This makes the code blocks really tall and IMHO you lose context with the rest of the post.

<img width="878" alt="screen shot 2018-12-21 at 4 28 30 pm" src="https://user-images.githubusercontent.com/205275/50364489-1fbb7180-053e-11e9-93f8-de223414ca82.png">

Personally I find a `line-height: 18px` to look much cleaner, that is ~1.25x the font height.

<img width="880" alt="screen shot 2018-12-21 at 4 27 59 pm" src="https://user-images.githubusercontent.com/205275/50364493-2518bc00-053e-11e9-837e-c80d74433edb.png">

I don't suppose there is any chance of changing this...

**Comment by jennybc** [comment]
The size of code in headings also looks a bit odd:

<img width="450" alt="screen shot 2018-12-21 at 4 40 25 pm" src="https://user-images.githubusercontent.com/599454/50368585-2dbdc200-053f-11e9-8927-5e6ef233f438.png">

from https://www.tidyverse.org/articles/2018/11/tibble-2.0.0-pre-announce/#deprecation-of-validate-in-as-tibble-https-tibble-tidyverse-org-dev-reference-as-tibble-html

**Comment by hadley** [comment]
@jimhester that looks slightly too cramped to me, but I agree that the default is too big. Want to do a PR that's somewhere in between?
