### ISSUE TITLE
Implement page bundles

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/tidyverse.org#279]
See @apreshill's post here: https://alison.rbind.io/post/2019-02-21-hugo-page-bundles/

**Comment by hadley** [comment]
_finally_!

**Comment by batpigandme** [comment]
@hadley, the trick will be to ensure we don't break your `slug-sq.jpg`, `slug-wd.jpg` magic 😜

**Comment by apreshill** [comment]
I have better ideas to fix this!

**Comment by batpigandme** [comment]
@apreshill, awesome!

**Comment by apreshill** [comment]
In short, I think some small changes in the layout files using Hugo's built in image processing (https://gohugo.io/content-management/image-processing/) with a single "featured.jpg" file in each bundle. I'll test my idea out today and report back.

**Comment by batpigandme** [comment]
Great. We have the two images because one is the thumbnail on the landing page, and the other the header for the actual post, but clarifying the featured image would be great.

**Comment by batpigandme** [comment]
Closed in #350
