### ISSUE TITLE
Add netlify deployment status badge

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/tidyverse.org#280]
Figure it's a nice way of sharing the netlify love (they released them on [Jan 29](https://www.netlify.com/blog/2019/01/29/sharing-the-love-with-netlify-deployment-badges/)). (@hadley, you're the only one who has access, I think). It's in:
**Settings > General > Netlify status badges**

**Comment by jennybc** [comment]
I also like the convenience of clicking on it, like travis and appveyor badges, to work my way over to the logs sometimes.

**Comment by jennybc** [comment]
I just plopped it in there @batpigandme. Feel free to do more, but now you've got the actual badge URL to work with.
