### ISSUE TITLE
Too much vertical padding on code

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidyverse.org#309]
e.g. there should be white space between these lines

<img width="503" alt="image" src="https://user-images.githubusercontent.com/4196/57302292-74e8c180-70a0-11e9-9cfa-2c0e843778c6.png">

**Comment by jimhester** [comment]
Looks like this is coming from 

https://github.com/tidyverse/tidyverse.org/blob/b5da7bbb1472dcaac9fa073c7c4aabe885883ddd/static/css/tweaks.css#L2

Just removing the `margin: 0` line fixes it, but possibly may cause other undesired changes.

**Comment by hadley** [comment]
For reference blog post is https://www.tidyverse.org/blog/2019/05/vroom-1-0-0/

**Comment by hadley** [comment]
Ok, the root problem is not actually the code blocks — its the padding between list elements. Most lists appear to get a `<p>` embedded within the `<li>`, but some (like this one, do not). A good example of this is <https://www.tidyverse.org/blog/2020/04/usethis-1-6-0/> — under github actions, the first list is just `<li>...`, the second is `<li><p>...`

Fortunately it looks like we can just add a margin to the bottom of `<li>` and the margin collapsing rules means that it still looks ok with the other form.
