### ISSUE TITLE
Links to posts re. tidyverse dev day in Toulouse

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/tidyverse.org#330]
Feel free to reply with your links. If not yours, please include attribution.
Thanks

**Comment by lauracion** [comment]
ICYMI (likely not :smile: ) there is a section for Tidyverse Dev Day in Toulouse [here](https://lacion.rbind.io/post/my-first-user/)

**Comment by maelle** [comment]
I came here to post the link to Laura's post that I'm reading right now! "A really friendly coding environment and the right incentives can make a sleep-deprived newbie make their first contribution to open source." 😁 end of thread hijack 😇

**Comment by jennybc** [comment]
https://www.mango-solutions.com/blog/user2019-roundup-workflow-reproducibility-and-friends
