### ISSUE TITLE
styler v1.2.0 post

### ISSUE THREAD

**Issue by lorenzwalthert** [tidyverse/tidyverse.org#346]
For styler v1.0.0, I was invited to write a [blog post](https://www.tidyverse.org/articles/2017/12/styler-1.0.0/) on styler. That was in December 2017. We are about to go to [v1.2.0](https://github.com/r-lib/styler/pull/556), so I wonder if it would be appreciated if I'd write a blog post about what happened since then and quickly discuss the, say top 10, new features since the initial CRAN release.

**Comment by hadley** [comment]
Yes, that'd be great!
