### ISSUE TITLE
Add tidyverse-specific archetype content

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/tidyverse.org#352]
Won't work until https://github.com/batpigandme/tidyverse.org/issues/21 is resolved, but:

* Rmarkdown setup chunk
* knitr output to `/fig` subdirectory
* Description field
* Chunk indicating that we need to load the library for the post (if not, add this to contributing guidelines, see also https://github.com/batpigandme/tidyverse.org/issues/17)

**Comment by jennybc** [comment]
To elaborate on standard stuff (I think it's easier for people to delete this, if unnecessary, than to remember it or find in contributing):

  * Lead off with "The foofy package makes THIS easier by doing THAT ...".
  * Include an early and obvious link to package's website, preferably in this form <https://tidyr.tidyverse.org>
  * Invite people to read full details in the "change log" or "release notes", which is a link to the relevant section of NEWS on the pkgdown site.
  * "Install foofy with" then a chunk with `install.packages("foofy")`
  * Show `library("foofy")`
  * Stub for a "thanks" section

**Comment by jennybc** [comment]
I generally prefer to get dumped quickly into a `.md` (or `.Rmarkdown` or whatever) document with placeholders for me to populate or delete. As opposed to having to complete a form, which is what I think the addin will feel like. Some of this stuff will require copy / pasting from elsewhere and I'd rather do that in "editing" mode than "form-filling" mode.

**Comment by jennybc** [comment]
I would lean towards making the form minimal, i.e. elicit just what is needed in order to create the necessary folders and files. And, I guess, anything where drop-down assistance is really nice, in terms of knowing what values you've got to choose from (e.g. tags).

**Comment by batpigandme** [comment]
Agreed — I think the slug is the only strictly necessary item for folder generation, but the dropdowns work really nicely for categories/tags (as you mentioned). I think I'll aim for a minimal version that errs on the side of prompt-ish, then, rather than trying to fill in the blanks.

**Comment by hadley** [comment]
It's also worth considering that the form will always require some hacking to remove the day from the url. A usethis function could handle that for us automatically

**Comment by batpigandme** [comment]
Yeah, I've been tinkering with that (getting the addin to drop the day) to no avail, thus far.

**Comment by apreshill** [comment]
Just a note- the addin is standard in blogdown- nothing in the archetype changes the addin. The archetype will get "dumped" into your .Rmarkdown or .md file. You can see the current ones without the addin using the terminal:

```
hugo new blog/help-me
```

**Comment by batpigandme** [comment]
Note to self to see also Leo's post
https://lcolladotor.github.io/2018/03/08/blogdown-archetype-template/

**Comment by jimhester** [comment]
> It's also worth considering that the form will always require some hacking to remove the day from the url.

Couldn't we do something in blogdown or the addin to prevent this?

**Comment by batpigandme** [comment]
> Couldn't we do something in blogdown or the addin to prevent this?

@jimhester, yeah, so I haven't quite figured out the right approach here. Using `blogdown::new_post()` has a bunch of advantages (that @apreshill can describe much better than I can). The three-part-date thing is directly in blogdown, not hugo.

By default it uses `Sys.Date()` for the date, which is used to make the filename. That can be overridden manually, but there's a `tryCatch()` checking to see if the date is in the future, so it doesn't take kindly to anything that's not a real date.

https://github.com/rstudio/blogdown/blob/a93ae13155050d76ab8eaae62f31d32e6471bc07/R/hugo.R#L316-L338

**Comment by jimhester** [comment]
Can we supply the `file` argument directly then, rather than having it be generated from the `date`?

**Comment by batpigandme** [comment]
Yes, that should be possible. I'm just waiting to confirm with Alison — in Hugo you can specify that you want only part of a date in the slug (like we use). It would be preferable to reference that option (esp. since the addin is useful for tag/category control), but the `file` argument should work regardless. (I didn't even realize that was a thing until this morning 😳 )

**Comment by hadley** [comment]
Solved by hugodown conversion
