### ISSUE TITLE
Make sure generated figures go to post subdirectory

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/tidyverse.org#357]

**Comment by batpigandme** [comment]
Add to setup chunk:

```
knitr::opts_chunk$set(fig.path = "figs/")
```

_n.b._ (per @apreshill) blogdown default will be to go to static no matter what, so this will be moving forward only.

**Comment by hadley** [comment]
And need to fix ggplot2 post that missed this

**Comment by hadley** [comment]
Solved by hugodown conversion
