### ISSUE TITLE
The package icon is missing for the article categories

### ISSUE THREAD

**Issue by LucyMcGowan** [tidyverse/tidyverse.org#36]
I believe this is because the category specified in the `css` is "package", whereas the category specified in the articles is "packages":
https://github.com/tidyverse/tidyverse.org/blob/21f82db97fac49163c8d4b5307b557f00bdbaf64/static/css/tidyverse-site.css#L802-L803

I suppose it'd be easier just to change the css? I'm happy to do the 📦 PR, just wanted to run this by you first.

**Comment by hadley** [comment]
I'd prefer to avoid changing the css since it's generated by Robby and I just include a copy.

**Comment by LucyMcGowan** [comment]
ah 👌 then should everyone change to "package" instead of "packages" for the category?

I think this effects 3 articles:
* http://www.tidyverse.org/articles/2017/08/googledrive-initial-release/  
* http://www.tidyverse.org/articles/2017/08/tidyr-0.7.0/  
* http://www.tidyverse.org/articles/2017/08/purrr-0.2.3/

I just felt like it looks a bit sad empty :confused:
<img width="243" alt="no_pkg_icon" src="https://user-images.githubusercontent.com/8431897/29840608-34984b68-8cc8-11e7-9a23-d78061b9f107.png">

**Comment by hadley** [comment]
Yes please!
