### ISSUE TITLE
Set up nightly rebuild with github actions

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/tidyverse.org#361]
See post here: https://www.voorhoede.nl/en/blog/scheduling-netlify-deploys-with-github-actions/

**Comment by jimhester** [comment]
What is changing that requires a nightly rebuild?

**Comment by batpigandme** [comment]
It is. Though refreshing events might be necessary… Really, @hadley told me to do it! 😜

**Comment by hadley** [comment]
It's completely static apart from the events, which need to automatically roll off the home page when complete.
