### ISSUE TITLE
Reflect change from retired to superseded 

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidyverse/tidyverse.org#384]
https://www.tidyverse.org/lifecycle/

**Comment by batpigandme** [comment]
There's some nuance here, which is better suited to the lifecycle package. superseded is for functions, as opposed to packages, I believe.

**Comment by jennybc** [comment]
I'd like a ruling on this too. This relates to https://github.com/r-lib/usethis/pull/1004 which changes "retired" to "superseded" in the lifecycle-related functions of usethis.

**Comment by hadley** [comment]
I think we should use superseded for both functions and packages.

**Comment by hadley** [comment]
Somewhat related, I am also wondering if maturing only makes sense for packages, not functions.
