### ISSUE TITLE
Rendering of packages page messed up

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidyverse.org#404]
https://www.tidyverse.org/packages/

Probably due to my change to use new markdown engine

**Comment by EconomiCurtis** [comment]
This issue has been noticed since. After ggplot2 and the errant `</div>`, no other tidyverse packages are listed. 
![image](https://user-images.githubusercontent.com/4430330/78831798-18241400-799f-11ea-849c-bf65c3ef1531.png)
