### ISSUE TITLE
Figure out how to avoid re-rendering old posts

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/tidyverse.org#406]
Currently, old posts that haven't been changed are getting re-rendered when contributors try to render the site (i.e. run `blogdown::serve_site()`). We want to avoid this (for obvious reasons). cc @apreshill

**Comment by hadley** [comment]
I think this is a fundamental flaw with the design of blogdown/hugo, and I suspect @jennybc's hack at  https://github.com/tidyverse/tidyverse.org#troubleshooting is the best we can do.

**Comment by hadley** [comment]
Solved by conversion to hugodown.
