### ISSUE TITLE
Correct README instructions re. adding events

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/tidyverse.org#422]
Currently in the README:
> `data/events.yaml`: this yaml file contains information about upcoming events. The site automatically filters out events that have happened, sorts by date, and then shows at most two events.

This is no longer true. Should reflect tidyverse version of what's in `conent/events` bundles, which I believe is slightly different to what the education site is doing, since there are full-blown posts in theirs.

**Comment by apreshill** [comment]
We actually deactivated the education site posts in favor of linking out too. Perhaps we should link this to https://github.com/tidyverse/tidyverse.org/pull/271 as there is an existing event archetype if you use the "new post" add-in.

**Comment by batpigandme** [comment]
Sounds good. Working on #113 right now, and I didn't want to miss this piece.

**Comment by hadley** [comment]
Should now just be `hugodown::post_create("events/event-name")` (need to test then add to `README.md`)
