### ISSUE TITLE
typo found on https://dbplyr.tidyverse.org/articles/backend-2.html

### ISSUE THREAD

**Issue by yitao-li** [tidyverse/tidyverse.org#493]
Minor issue: `dbQuoteIdentifer()` should be replaced with `dbQuoteIdentifier()` -- I only found it because I'm the maintainer of another R package that needs to work with the new edition of `dbplyr` and I was copy/pasting things from the backend-2.html page.

Would be nice to get it fixed so that other DB backend authors working with `dbplyr` won't need to go through the same trouble.

**Comment by yitao-li** [comment]
Proposed fix: https://github.com/tidyverse/dbplyr/pull/571

**Comment by batpigandme** [comment]
Hi Yitao,
If you haven't already, could you open the issue for this in the dbplyr repo? We keep track of the pkgdown sites in the respective package repos, since that's where the content comes from.

I'm gonna close this here, since you can't close issues in one repo from another.

Thanks

**Comment by hadley** [comment]
(@batpigandme not important here, but very weirdly you can actually close issues in repo A in a commit message in repo B)

**Comment by batpigandme** [comment]
😳  Well, TIL…
