### ISSUE TITLE
Page not found (404)

### ISSUE THREAD

**Issue by thuettel** [tidyverse/tidyverse.org#520]
I'm frequently visiting the [reference for ggplot2 theme options](https://ggplot2.tidyverse.org/reference/theme.html). For a couple of days already the link to the [margin reference](https://ggplot2.tidyverse.org/reference/margin.html) which sits behind components like `element_text()` or `element_rect()` is not working any more and just showing the error message `Page not found (404)`.

I tried different OS (Windows/Mac), different Browsers (Firefox/Opera) and also deleting the Browser Cache.

**Comment by batpigandme** [comment]
Can you please file an issue in the ggplot2 repo? 

https://github.com/tidyverse/ggplot2/

The pkgdown sites (<pkg_name> dot tidyverse dot org) are generated by the documentation for the individual packages, so that's where to go to fix the issue.

Thanks
