### ISSUE TITLE
Photos for future posts

### ISSUE THREAD

**Issue by jennybc** [tidyverse/tidyverse.org#69]
A place to park photos we come across.

**Comment by jennybc** [comment]
Re: whether models/VMS/whatever are pets vs livestock

<img src="https://cdn.gratisography.com/photos/91H.jpg" width="400">
from https://gratisography.com

**Comment by jennybc** [comment]
<img src="https://images.unsplash.com/photo-1505763169286-d69f372b4652?auto=format&fit=crop&w=3063&q=80" width="400">

from @hadley, <https://unsplash.com/photos/DDXpun_CQR0>

**Comment by jennybc** [comment]
"`<THING>` is like a box of chocolates. You never know what you're gonna get." -- Forrest Gump

`<THING>` is typically `sapply()`

from https://gratisography.com

**Comment by hadley** [comment]
Closing since it's two years old, and we clearly forgot to regularly revisit this issue.

**Comment by jennybc** [comment]
https://unsplash.com/photos/kY2H30v6Bs4

![john-cameron-kY2H30v6Bs4-unsplash](https://user-images.githubusercontent.com/599454/160502096-a393fb85-45db-4c2e-9949-ef85d4d4f51c.jpg)
