### ISSUE TITLE
Remove renegade read-more 🔗 on articles page

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/tidyverse.org#76]
Possibly related to https://github.com/tidyverse/tidyverse.org/commit/e8fcdfbfea697ea011c8280b423da3d296e1b5f7 (though I'm not sure how), but there's a Read More link at the bottom of the [articles](https://www.tidyverse.org/articles/) page that goes to an un-styled version of Jenny's workflow post at <https://www.tidyverse.org/articles/1/01/>.

Visual depiction:
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/831732/34520349-482c450c-f056-11e7-9c12-959904d5e176.png">

**Comment by jennybc** [comment]
For me, all the "Read more..."s link to what I would expect.

But I've definitely noticed they do not during either local preview or Netlify preview, when I'm working on a post. @batpigandme could you be in one of those situations?

**Comment by batpigandme** [comment]
Yeah, I can't even find the source of that link...there's no parent article in the articles directory. 🤔

**Comment by hadley** [comment]
There’s a super weird article right at the bottom - also has bad date.

**Comment by batpigandme** [comment]
Or Jenny found the fountain of youth, and has been thinking about workflows since the year 1 A.D. 😛.

I rebuilt from https://github.com/tidyverse/tidyverse.org/pull/61, and there was no extra article at the bottom. Rebuilt from current, and it's still there.

**Comment by jennybc** [comment]
@batpigandme This is a fruitful approach. Can you do based on commit/SHA instead of PR? It should pinpoint the exact commit and it's clear the addition of my post is the hotspot. I was having emoji troubles but have no idea how could be related.

**Comment by batpigandme** [comment]
Yep, working on it! I now see why that merge I did was such a bad idea (lost granularity), but SourceTree is getting me closer… I've got it down to something between `2739e0abed8947a38980634229101550bcefab59` and `8ff8db025b28ad395c76621a60159bd2b726cbc4`.

**Comment by batpigandme** [comment]
Ok, yeah. So, the only commit between the two listed above is one where I changed the date on a post (which was later changed again), but even if I build from that commit (ecf10a98927e788c94768d528a56381e863a86b6), there's no weird link.

There are only four files changed in 2739e0a, none of which are the list partial (what makes that index page), and the only thing I can think of is that there's a weird generated version of that workflow article somehow stuck in the wires somewhere (I'll take a look at netlify).

**Comment by batpigandme** [comment]
Netlify previews of above-mentioned commits: 
https://deploy-preview-64--tidyverse-org.netlify.com/articles/

https://deploy-preview-63--tidyverse-org.netlify.com/articles/

**Comment by batpigandme** [comment]
Ooh, found non-preview deploys (or whatever the ones on netlify that aren't real previews are called) _with_ Jenny's workflow post, but _without_ the weird link. Also for earlier previews for 64.
https://5a2e69c3819876096d362a9d--tidyverse-org.netlify.com/articles/
https://5a2e6cb90b79b71803d5d623--tidyverse-org.netlify.com/articles/

Last workflow deploy _without_ link issue:
https://5a2e6d108198762157362ac8--tidyverse-org.netlify.com/articles/
First of same _with_ link issue:
https://5a2f53e7df995377b9da2fe2--tidyverse-org.netlify.com/articles/

**Comment by batpigandme** [comment]
OK, so I found the source file _locally_, but (AFAICT) the `public` folder isn't listed on github (and, thus, I don't know how to delete it from here). No clue how it got there but there is, indeed an index file in `public >> articles >> 1 >> 01`. 

<img width="528" alt="image" src="https://user-images.githubusercontent.com/831732/34541852-e4db05f4-f0a7-11e7-85f0-6477d8190a3b.png">

**Comment by jennybc** [comment]
I'm going to offer a highly technical suggestion: is there a way to power cycle netlify? Somehow this got into the cache and this might be the easiest way to get it back out.

**Comment by batpigandme** [comment]
Looking into it. Plot twist: when I remove it from public (locally) and then `blogdown::serve_site()` it _does_ regenerate, which surprises me... Hugo has some fancy automatic path finding stuff, that can also take things over a bit too much sometimes.

**Comment by batpigandme** [comment]
I'm able to go back to ecf10a98927e788c94768d528a56381e863a86b6 (which builds without the link), and then add @jennybc's workflow post and images without any problem (same when I make the changes from e8fcdfbfea697ea011c8280b423da3d296e1b5f7 , @hadley's mod to the Read More/list template, which is the only thing that seemed vaguely related).

It _doesn't_ go away if I just remove and replace the workflow post from an up-to-date branch… (The 1 and 01 folders in public show up if you go to any branch beyond the workflow posts, even though they don't have a parent file that I can find). 

Jenny, does this sound like a possible cherry-picking fix?

**Comment by jennybc** [comment]
Does this sound reasonable?

You create a **new branch** with parent at the last known good state. Then rebuild the site to current state, except without the phantom article. Cherry pick existing commits whenever possible. Push to GitHub **after every commit** (remember, you're in a branch and can't hurt master) and don't move on until the Netlify preview verifies absence of phantom. Once you have a branch with a history that gets us to our happy place, one of us could, locally, reset master to that branch and do a force push. That part is high risk, but might be unavoidable. But you could get everything worked out beforehand.

**Comment by hadley** [comment]
I'd rather just use that approach to figure out what the problem is, then manually fix it on master.

**Comment by batpigandme** [comment]
Sounds good. @hadley, I'll try my best to find a fixable source— so far I've only been able to identify a commit, but not any of its files, which is puzzling.

**Comment by batpigandme** [comment]
OK, have a copy working with all commits other than those related to the workflow post: https://cranky-cori-3407d0.netlify.com/articles/
