### ISSUE TITLE
Wording in import section of packages

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [tidyverse/tidyverse.org#77]
Currently it says "There are a handful of other packages that are not in the tidyverse, but are tidyverse-adjacent. They are very useful for importing data from other sources:" and lists jsonlite, xml2, httr, rvest, and DBI under this. It's unclear to me what the difference of these from readxl and haven is since all of these packages are installed with tidyverse but are not in the core. It might be more clear to list all in the same hierarchy (as is the case in the tidyverse repo README).

**Comment by batpigandme** [comment]
Just getting back to this now— the distinction that _I_ can see is that they're not tidyverse repos: [httr](https://github.com/r-lib/httr) and [xml2](https://github.com/r-lib/xml2) are in r-lib, [jsonlite](https://github.com/jeroen/jsonlite) is Jeroen's, [rvest](https://github.com/hadley/rvest) is still a hadley repo, and DBI isn't on the [tidyverse repo list](https://github.com/tidyverse/tidyverse#packages) to which I believe you're referring.

None of the above is to say that it's clear to anyone reading the site; but, given they _also_ don't have tidyverse pages (package.tidyverse.org), I can imagine it being slightly confusing not to differentiate at all. _That_ said, I'm not opposed to changing it as you've described at all. Just kind of digging around to figure things out.

**Comment by hadley** [comment]
Yeah, maybe we should move all those packages into an affiliates section? Or friends maybe? They're installed with the tidyverse package, but they're not members of the tidyverse organisation.  Or is that another layer that's just too confusing?

**Comment by batpigandme** [comment]
Oh, interesting. I didn't realise that blob, hms, modelr, and broom didn't have associated pages, so at least one part of my reasoning has crumbled.

**Comment by mine-cetinkaya-rundel** [comment]
I think with a brief definition of the layers on top of the page, another layer wouldn't necessarily make things more confusing.

**Comment by hadley** [comment]
They should all have pages though

**Comment by batpigandme** [comment]
Should I file issues for pkgdown pages for now?

**Comment by hadley** [comment]
Yes please!
