### ISSUE TITLE
Add lifecycle badge definitions

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/tidyverse.org#80]
See https://github.com/r-lib/usethis/issues/193#issuecomment-355624042
```
 #' * Experimental: very early days, a lot of churn in search of a good API. 
 #'   Not on CRAN. Might not go anywhere. Use with care. 
 #' * Maturing: API roughed out, but finer details likely to change. Will strive 
 #'   to maintain backward compatibility, but need wider usage in order to get 
 #'   more feedback. 
 #' * Dormant: not currently working on it, but plan to come back to in the 
 #'   future. 
 #' * Stable: we're happy with the API, and the unlikely to be major changes. 
 #'   Backward incompatible changes will only be made if absolutely critical, and 
 #'   will be accompanied by a change in the major version. 
 #' * Questioning: no long convinced this is a good approach, but don't yet 
 #'   know what a better approach might be. 
 #' * Retired: known better replacement available elsewhere. Will remain 
 #'   available on CRAN. 
 #' * Archived: development complete. Archived on CRAN and on GitHub. 
```

**Comment by hadley** [comment]
I'd suggest a new page `lifecycle` html that contains each of these as a h1, so we can link to with e.g. `tidyverse.org/lifecycle#experimental` 

Should include overview image at top 
![lifecycle](https://user-images.githubusercontent.com/4196/34624638-0837ea9e-f224-11e7-8b5a-83cf49b8602e.png)

**Comment by batpigandme** [comment]
Copy that. I did pretty much that, just used h3 because h1s look so big, but the anchors still work the same

**Comment by batpigandme** [comment]
Ignore the four attempts on various branches of my fork. This shows up at what _will be_ tidyverse[dot]org/lifecycle/
Preview: https://deploy-preview-81--tidyverse-org.netlify.com/lifecycle/ 
As requested, anchos with the name of each badge at `/lifecycle/#badge`
(e.g. https://deploy-preview-81--tidyverse-org.netlify.com/lifecycle/#maturing )

**Comment by maurolepore** [comment]
I see that lifecycle badges are increasingly used not only to refer to packages but also to functions within packages. But the definition of each stage remains focused on packages. 

The solution may be as simple as replacing 'package' with 'package/function'. E.g. 

> We are no longer convinced that a questioning package/function is the optimal approach, but we don’t yet know what a better approach is.

**Comment by batpigandme** [comment]
Since this issue is closed, can you please open a new one specifying that it would be badge definitions as they apply to functions? 

Thanks
