### ISSUE TITLE
Tidyverse courses

### ISSUE THREAD

**Issue by csgillespie** [tidyverse/tidyverse.org#87]
We've just launched a tidyverse course (https://www.jumpingrivers.com/courses/22_r-tidyverse)

Would it be appropriate to list it at https://www.tidyverse.org/learn/?

Thanks

**Comment by hadley** [comment]
Yup, please file a PR!

**Comment by csgillespie** [comment]
Great. There are currently three headings:

 * Books
 * Online courses
 * University courses

Should I create a new heading, say "On-site courses"

**Comment by hadley** [comment]
I'd call those workshops
