### ISSUE TITLE
Add 1.2.0 core hex badges (stringr & forcats) to main page?

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/tidyverse.org#95]
https://github.com/tidyverse/tidyverse.org/blob/7653fd2c97cb74c3a69fe06d2fa7eca94ea23177/layouts/index.html#L7

@hadley _this_ is the section I was confused about in terms of hex placement yesterday— I didn't want to mess up the look.

![Imgur](https://i.imgur.com/gyeYlkL.png)

**Comment by hadley** [comment]
Oh yeah, that needs Robby's magic

**Comment by hadley** [comment]
Maybe we can re-look at this now?
