### ISSUE TITLE
Broken link to pkgdown in footer of page about each package

### ISSUE THREAD

**Issue by gregrs-uk** [tidyverse/tidyverse.org#96]
e.g. http://ggplot2.tidyverse.org

Link to pkgdown in bottom-right corner of page is broken (http://hadley.github.io/pkgdown/ gives a 404 error)

**Comment by gregrs-uk** [comment]
PR submitted in tidytemplate repo

https://github.com/tidyverse/tidytemplate/pull/6

**Comment by hadley** [comment]
Thanks! @batpigandme has opened individual issues in each repo, so this fix will gradually roll out as those sites are updated.
